DorianLudm/Appli_Pompiers

site_web/static/css/ajout_compte.css
site_web/views.py

Correction des erreurs suite au précédent merge

Correction d'erreurs CSS et désaction du scroll

---

site_web/static/css/recherche_doc.css
site_web/templates/recherche_doc.html

mise à jours templates

---

site_web/models.py
site_web/templates/rechercheComptes.html
site_web/views.py

Bouton supprimer compte implémenté

Feature supprimer compte

---

site_web/static/css/accueil_admin.css
site_web/static/css/header.css
site_web/templates/informations_utilisateur.html

Modifications des éléments suivants afin de les rendre responsives:
- h1
- img
- input

Responsive header

---

site_web/templates/recherche_doc_admin.html

AJout du bouton pour ajouter un document, lien fait avec la page permettant d'ajouter un document

Ajout du bouton pour ajouter un document

---

site_web/static/css/recherche_comptes.css
site_web/templates/rechercheComptes.html

Ajout du bouton pour retourner à l'accueil directement

Ajout du bouton pour retourner à l'accueil

---

site_web/static/css/recherche_comptes.css
site_web/templates/rechercheComptes.html

Fix décalage dans "rechercheComptes.html" sur la ligne de notre compte

---

site_web/views.py

Correction d'une erreur lors de la suppression d'un seul tag

Correction erreur suppression d'un tag

---

installations_pip.sh
site_web/static/css/accueil_admin.css
site_web/static/css/gerer_tags.css
site_web/templates/accueil_admin.html
site_web/templates/gerer_tags.html
site_web/views.py

Correction de la responsivité de l'accueil administrateur
Ajout page gerer tags en maintenance

Correction responsive accueil admin

---

site_web/static/css/ajout_compte.css
site_web/templates/ajoute_compte.html
site_web/templates/modifierCompte.html
site_web/templates/recherche_doc.html

Rectification CSS modifier un compte

Rectification CSS modifier un compte

---

site_web/static/css/accueil_admin.css
site_web/templates/accueil_admin.html

Changement du bouton "Gerer Tags" de l'accueil admin par le bouton "Rechercher des documents"
Changement du responsive pour prendre en compte le changement.

Changement bouton accueil admin

---

site_web/views.py

Correction erreur ajout tag manuel et type ajout document

---

site_web/views.py

fix erreur suppression document maj affichage

---

site_web/models.py
site_web/views.py

Fix le fait de pouvoir ajouter 2 tags identiques aux filtres, en particuleir en utilisant "." dans la barre de recherche.
=> Rajout d'un __hash__ et __eq__ pour les Tags

Fix TAGs en double

---

installations_pip.sh
site_web/generationTag.py

Version 1.0 du fichier pour genererTag

Feature generation tag

---

site_web/static/css/recherche_tag.css
site_web/templates/recherche_tags.html

Finalisation CSS de la page gestion des tags

---

site_web/app.py
site_web/static/js/personnalisationTags.js
site_web/templates/recherche_tags.html

Ajout de la personnalisation des tags :
- changement couleur
- changement nom

Personnalisation des tags

---

site_web/views.py

Enleve le tag suprimmer des tags actifs

---

site_web/static/js/personnalisationTags.js

Fix noms invalides (pas de caractères, juste des espaces par ex => affiche une alerte et ne modifie pas le nom)

Fix nom des tags

---

site_web/templates/mdp_oublie.html

Bouton retour pour revenir à la page de connexion depuis la page de mot de passe oublié.

Bouton retour

---

site_web/static/css/header.css
site_web/templates/informations_utilisateur.html

Changements apportés sur le header afin de le rendre moins imposant

Refonte du header

---

site_web/static/css/ajout_compte.css
site_web/static/css/ajouter_document.css
site_web/templates/ajoute_compte.html
site_web/templates/ajouter_document.html
site_web/views.py

Rectification du CSS de certains boutons de validation & annulation.

Correctifs CSS Boutons

---

site_web/models.py
site_web/templates/recherche_tags.html
site_web/views.py

Possibilité de rechercher un tag par nom, et de reset les filtres sur la page de gestion des tags

Création de la recherche sur la page des tags

---

site_web/static/css/ajout_compte.css
site_web/static/css/header.css
site_web/templates/modifierCompte.html

FIX CSS dû à la refonte du header + petite diminution de la _height_ du header (fix 1 media en vw et l'autre en vh, mtn les 2 sont en vh)

FIX CSS dû à la refonte du header

---

site_web/models.py
site_web/views.py

Lorsqu'un document est supprimé, la liaison dans favoris l'est
Lorsqu'un document est supprimé, la liason doctag l'est aussi
Lorsqu'un utilisateur est supprimé, la liaison dans favoris l'est
Lorsqu'un tag est supprimé, la laison doctag l'est aussi

Ajout d'optimisations
